### ISSUE TITLE
Artifacts uploaded multiple times with docs/sources enabled

### ISSUE THREAD

**Issue by ToxicBakery** [gradle-fury/gradle-fury#37] opened 2016-12-01 16:18 UTC
With javadoc and sources enabled, jar libraries are uploaded multiple times which breaks setups not using staging (aka push to release).

I have created a sample project to demonstrate the issue
https://github.com/ToxicBakery/gradle-fury-example

Using
`./gradlew build publish --continue -Pprofile=sources,javadoc --stacktrace`

Results in:
https://gist.github.com/ToxicBakery/e90a370b43557427eaa54ad98a3d20ff

Note that the jar, pom, and their signing and hashing are all uploaded 3 times each. Using the same process for an Android AAR the expected result happens that the AAR and pom is uploaded once while the javadocs and sources are also uploaded nominally and without issue.

Error example on upload
```
Upload http://10.0.0.90:8080/repository/internal/com/somelibrary/gradle/mylibrary/1.0.368/mylibrary-1.0.368.pom
Could not transfer artifact com.somelibrary.gradle:mylibrary:pom:1.0.368 from/to remote (http://10.0.0.90:8080/repository/internal/): Could not write to resource 'com/somelibrary/gradle/mylibrary/1.0.368/mylibrary-1.0.368.pom'
```

Stacktrace:
https://gist.github.com/ToxicBakery/e8ee5b197a8a0d32bb41248f7c1e0080

Simplified error:
`Received status code 409 from server: Overwriting released artifacts is not allowed.`

**Comment by spyhunter99** [comment] 2016-12-02 01:07
try
````
./gradlew build publishArtifacts --continue -Pprofile=sources,javadoc --stacktrace
````

Gradle's handling of artifacts isn't as good as it could be, so we overrode it

**Comment by ToxicBakery** [comment] 2016-12-02 21:13
`publishArtifacts` causes two separate issues.

1. This seems to force signing enabled. I did not try bringing my keys in as I do not have access to them at this moment so im not sure if it would work with signing properly configured. Since you use it I assume it does.

2. Given that I can not sign right now I tried disabling signing by setting `pgpSearch=true` so the signing checks would inherently return false. This successfully disabled signing but a new error occurs due to missing `pom-default.xml`

I genuinely share your frustration of the ridiculous amounts of work gradle inflicts on you to simply publish artifacts properly so thank you for this library and the comedy associated.

**Comment by spyhunter99** [comment] 2016-12-03 00:05
haha thanks. i'll look into it. Maybe we can convince gradle grand master @chrisdoyle to chip in.

**Comment by spyhunter99** [comment] 2016-12-03 00:09
So just for my understanding, we have two problems

1) using the build in `publish` command is jacked up because of the gradle-fury specific scripts
2) need to be able to support publishing artifacts without signatures
3) trap/solve whatever the issue is with pom-default.xml missing

for the last item, it may be solvable with this `gradlew install publishArtifacts --continue -Pprofile=sources,javadoc --stacktrace`. Give that a shot

In some cases, the pom file is only generated with the `install` task

**Comment by spyhunter99** [comment] 2016-12-03 00:33
@ToxicBakery I just ran your project on my machine (windows) and published to a release repo (local nexus install, but it's not a staging repo). I didn't see any evidence of it uploading more than one pom. I don't have gpg installed on the this machine and it spit out did spit out some stack traces but it was a warning about gpg. Here's my output

````
$ ./gradlew publishArtifacts -Pprofile=javadoc,sources
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at maven_support_8sq4facvlbszobph9iq0udtng.run(C:\projects\gradle-fury-example\gradle-fury\gradle\maven-support.gradle:1951)

   ----.--.     #####                                        #######
--/ _  |___)  #     #  #####    ##   #####  #      ######    #       #    # #####  #   #
     \_|____) #        #    #  #  #  #    # #      #         #       #    # #    #  # #
       |____) #  ####  #    # #    # #    # #      #####     #####   #    # #    #   #
---\___(__)   #     #  #####  ###### #    # #      #         #       #    # #####    #
               #    #  #   #  #    # #    # #      #         #       #    # #   #    #
                #####  #    # #    # #####  ###### ######    #        ####  #    #   #
                                                                     v1.1.1

== Gradle Fury, bringing maven sensibility to gradle. It's NOT an incubating feature.
== Gradle Fury: ProTip: Use 'gradle install' to publish to mavenLocal, works with AARs and APKs, even with variants
== Report Gradle Fury issues to: https://github.com/gradle-fury/gradle-fury/issues, also see the wiki for more info

 Building version 1.0.0 of your project...
:kotlin:publishArtifacts
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0.jar : 201: Created
org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/usr/local/bin/gpg''
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:198)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:329)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/usr/local/bin/gpg'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
        ... 5 more
Caused by: java.io.IOException: Cannot run program "/usr/local/bin/gpg" (in directory "C:\projects\gradle-fury-example\kotlin"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 8 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 9 more
GPG NOT found, signing will not be possible
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0.jar.md5 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0.jar.sha1 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0.pom : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0.pom.md5 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0.pom.sha1 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0-javadoc.jar : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0-javadoc.jar.md5 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0-javadoc.jar.sha1 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0-sources.jar : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0-sources.jar.md5 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/kotlin/kotlin/1.0.0/kotlin-1.0.0-sources.jar.sha1 : 201: Created
:vanilla-java:publishArtifacts
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0.jar : 201: Created
org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/usr/local/bin/gpg''
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:198)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:329)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/usr/local/bin/gpg'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
        ... 5 more
Caused by: java.io.IOException: Cannot run program "/usr/local/bin/gpg" (in directory "C:\projects\gradle-fury-example\vanilla-java"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 8 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 9 more
GPG NOT found, signing will not be possible
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0.jar.md5 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0.jar.sha1 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0.pom : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0.pom.md5 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0.pom.sha1 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0-javadoc.jar : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0-javadoc.jar.md5 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0-javadoc.jar.sha1 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0-sources.jar : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0-sources.jar.md5 : 201: Created
Upload http://localhost:8081/nexus/content/repositories/releases/com/gradle/fury/example/java/vanilla-java/1.0.0/vanilla-java-1.0.0-sources.jar.sha1 : 201: Created

BUILD SUCCESSFUL

Total time: 1.838 secs

````

**Comment by ToxicBakery** [comment] 2016-12-08 15:37
Sorry for the delay, I had a short trip to Europe that ate up all my time.

Running
`./gradlew clean install publishArtifacts --continue -Pprofile=sources,javadoc`

Results in publishArtifacts failing for  
`Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/local/bin/gpg'' finished with non-zero exit value 2`
at  
`gradle-fury/gradle/maven-support.gradle:2048`

---

Running
`./gradlew clean publishArtifacts -Pprofile=javadoc,sources`

Results in publishArtifacts failing for  missing the kotlin jar but that is clearly due to build not being called.

Task calls
```
:kotlin:clean UP-TO-DATE
:vanilla-java:clean UP-TO-DATE
:kotlin:publishArtifacts
     _.-^^---....,,--
 _--                  --_
<                        >)
|                         |
 \._                   _./
    ```--. . , ; .--'''
          | |   |
       .-=||  | |=-.
       `-=#$%&%$#=-'
          | ;  :|
 _____.,-#%&$@%#&#~,._____ 
:kotlin:publishArtifacts FAILED
```
_Off topic but I love the ascii art here._

So going off the notion of build not being called  
`./gradlew clean build publishArtifacts -Pprofile=javadoc,sources`

Is the same result as using `install` failing at `maven-support.gradle:2048` caused by `Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/local/bin/gpg'' finished with non-zero exit value 2` 

More detailed failure
```
[INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/usr/local/bin/gpg''
[ERROR] [system.err] gpg: cannot open `/dev/tty': Device not configured
```

So obviously something is incorrect in the GPG call (at least on OSX on my machine). Looking around I found a few suggestions and figured I would try `--no-tty` via the `signing.isInteractive` flag. This unfortunately also failed.

```
gpg-agent[3111]: command get_passphrase failed: Inappropriate ioctl for device
gpg: problem with the agent: Inappropriate ioctl for device
gpg: no default secret key: Operation cancelled
gpg: signing failed: Operation cancelled
```

I'm kind of at a loss from here. If I manually run GPG signing works properly and signing works properly using the chris banes script combined with the built in gradle signing plugin.

I feel like this has gotten off topic from the issue though. Would you like me to make a new issue for this problem?

**Comment by spyhunter99** [comment] 2016-12-08 23:25
I think if you add a "-d" to the command, you should eventually find the actual command that gradle fury is trying attempting to call during the signing. I wrote that portion of it on a mac, so it worked at one point in time. I'm on windows 10 now and no longer have a test environment for macos with gpg installed

You should also be able to set the gradle.properties ( or local.properties) setting GPG_PATH to something a file/path that doesn't exist. That should force the signing to skip as well

**Comment by spyhunter99** [comment] 2016-12-09 01:27
try switching over to gradle-fury's develop branch. I added a new command line option `-Pgpg.Skip` it may help your situation

**Comment by spyhunter99** [comment] 2016-12-18 14:00
a new release was cut a few days ago, give it a try again.

**Comment by spyhunter99** [comment] 2016-12-18 14:02
also, i'd like to partially merge your kotlin example into gradle fury tests/examples. is that a possibility? if not, i'll use your example as a model. I've never used kotlin before and it would be fun to give it a shot

**Comment by ToxicBakery** [comment] 2016-12-19 05:14
Sorry, been a busy few weeks. I'm totally for merging it in. I can create a PR for you if you like.

**Comment by spyhunter99** [comment] 2016-12-23 00:20
i'm working on the merge now. I see something strange though. fury is producing a pom listing the following as a dependency
````
 <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <scope>compile</scope>
      <version>1.0.5-2</version>
      <type>jar</type>
    </dependency>
````

is this a "real" dependency of the jar to run?

Edit: yes, yes it is

**Comment by spyhunter99** [comment] 2016-12-23 00:47
ugh, one more update. supporting kotlin looks to be a bit harder than i thought. the normal javadocs task doesn't work with it and another plugin is required for docs. Kotlin with android is also another problem area. i'll push my changes to feature/#37 but it will most likely die on the vine unless you (or someone else wants to put the time into it to fix these issues

edit: updates

**Comment by ToxicBakery** [comment] 2016-12-23 03:33
Yeah full support for Kotlin is still kind of beta. The language works fine but all the extra stuff you expect doesn't always work how you would think it would. Class and method documentation for instance still don't work properly in Intellij (maybe soon?) so I imagine javadoc output from Kotlin wont happen until at least that happens.

Another thing I have noticed, have you seen pom dependencies generate improperly? It seems if you have a multi module project that the generate pom does not properly reference the other modules so if you try to use transitive dependencies it will fail to discover the other deps due to missing the 'release' or 'debug' or whatever you build is producing. I believe it was only that field that is missing but I would have to look.

**Comment by spyhunter99** [comment] 2016-12-23 03:51
"release" and "debug" should map to dependency classifier statements. the classifier support is as good as i could get it with gradle, which isn't very good.

i'm actually rereading my javadoc comments here: https://github.com/gradle-fury/gradle-fury/blob/master/gradle/maven-support.gradle#L1012
it looks like classifiers aren't currently supported, because gradle doesn't expose that through the dsl. 

It looks like i had something in place here:
https://github.com/gradle-fury/gradle-fury/blob/master/gradle/maven-support.gradle#L1100 but it's commented out. I don't recall why. Probably because it didn't work for all cases and only worked for just a few, or maybe it only worked on some versions of gradle. 

Related: https://github.com/gradle-fury/gradle-fury/blob/master/gradle/maven-support.gradle#L1111
here's how i pick up the "type". There's only one mechanism i was able to find that dumped the complete list if file names of dependencies. it then scan that list for matches. Not 100% reliable but it works for most cases.

**Comment by ToxicBakery** [comment] 2016-12-23 03:54
That's good to know. Definitely prefer working builds over nice to haves like transitive.

I am updating my example lib right now and im going to add a travis config so we can all see the same things. I'll let you know when I make some progress on that.

**Comment by spyhunter99** [comment] 2016-12-23 03:58
see gradle-fury/feature/#37 I took your sample project and just moved the folder structure around.
amazingly it looks like it passed all of the ci tests, although the javadoc jar is empty. i guess it can be merged knowing that this is an issue.

**Comment by spyhunter99** [comment] 2016-12-24 14:33
kotlin sample has been merged with the knowledge that javadocs will generate an empty jar but will publish

**Closed as completed** 2016-12-24 14:33 UTC
Labels: in progress
